pcta_updated/main/urls.py
from django.conf.urls import url
from . import views

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
	url(r'^$', views.main_template, name='main_template'),
	url(r'^option/$', views.option, name='option'),
	url(r'^calculation/$', views.call_calculation, name='calculation'),
	url(r'^about/$', views.about, name='about'),
	url(r'^manual/$', views.manual, name='manual'),
	url(r'^QnA/$', views.qna, name='qna'),
	url(r'^download/$', views.download, name='download'),
	url(r'^file_download/$', views.file_download, name='file_download'),
	url(r'^image_download/$', views.image_download, name='image_download'),
	url(r'^association_result/$', views.association_result, name='association_result'),
	url(r'^correlation_result/$', views.correlation_result, name='correlation_result'),
	url(r'^bcr_result/$', views.bcr_result, name='bcr_result'),
	url(r'^set_result/$', views.set_result, name='set_result'),
	url(r'^calculation/poll_state$', views.poll_state,name='poll_state'),
	url(r'^pathway_input$', views.initial_change, name='pathway_input'),

	url(r'^favicon.ico$', RedirectView.as_view( url=staticfiles_storage.url('images/favicon.ico'),), name="favicon"),
]

pcta_updated/pcta_updated/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace='main')),
]

pcta_updated/main/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class AssocInputText(forms.Form):
	gene_input = forms.CharField(label='',required=False, widget=forms.Textarea(attrs={'placeholder': 'Copy and Paste Gene or Gene list(Entrez ID or Official Gene symbol)'}))
	def clean(self):
		value1 = self.cleaned_data['gene_input']
		value1_length = value1.split("\n")

		if len(value1_length) > 1000 and value1!='':
			raise forms.ValidationError("Input should be less than 1000")
		return value1

class CorrInputText(forms.Form):
	corr_input1 = forms.CharField(label='',required=False, widget=forms.Textarea(attrs={'placeholder': 'First Gene or Gene List (Entrez ID or Official Gene symbol)'}))
	corr_input2 = forms.CharField(label='',required=False, widget=forms.Textarea(attrs={'placeholder': 'Second Gene or Gene List (Entrez ID or Official Gene symbol)'}))
	def clean(self):
		value1 = self.cleaned_data['corr_input1']
		value1_length = value1.split("\n")
		value2 = self.cleaned_data['corr_input2']
		value2_length = value2.split("\n")

		if len(value1_length) > 1000 and value1!='':
			raise forms.ValidationError("Input should be less than 1000")
		if len(value2_length) > 1000 and value2!='':
			raise forms.ValidationError("Input should be less than 1000")

		if value1!='' and value2=='':
			raise forms.ValidationError("Please input second list for correlation")
		if value2!='' and value1=='':
			raise forms.ValidationError("Please input first list for correlation")
		return value1

class SetInputText(forms.Form):

	set_input = forms.CharField(label='',required=False, widget=forms.Textarea(attrs={'placeholder': 'Copy and Paste Gene list only (Entrez ID or Official Gene symbol)'}))
	def clean(self):
		value1 = self.cleaned_data['set_input']
		value1_length = value1.split("\n")

		if len(value1_length) > 1000 and value1!='':
			raise forms.ValidationError("Input should be less than 1000")
		if len(value1_length) < 3 and value1!='':
			raise forms.ValidationError("Input should be more than 3")
		return value1

class AssocOptionForm(forms.Form):
	choice_option = [('n_category', 'By Disease Course'), ('pcs', 'By PCS'), ('pam50', 'By PAM50'), ('bcr', 'By BCR')]
	sample_option = forms.ChoiceField(widget=forms.RadioSelect, label='', choices=choice_option, required=True, initial=['n_category'])

class CorrOptionForm(forms.Form):
	choice_option = [('n_category', 'By Disease Course'), ('pcs', 'By PCS'), ('pam50', 'By PAM50')]
	sample_option = forms.ChoiceField(widget=forms.RadioSelect, label='', choices=choice_option, required=True, initial=['n_category'])

class SetOptionForm(forms.Form):
	choice_option = (('By Disease Course', (('n_category:GS<7', 'GS<7 VS Others'), ('n_category:GS=7', 'GS=7 VS Others'), ('n_category:GS>7', 'GS>7 VS Others'), ('n_category:mCRPC', 'mCRPC VS Others'))), ('By PCS', (('pcs:PCS1', 'PCS1 VS Others'), ('pcs:PCS2', 'PCS2 VS Others'), ('pcs:PCS3', 'PCS3 VS Others'))), ('By PAM50', (('pam50:LumA', 'Luminal A VS Others'), ('pam50:LumB', 'Luminal B VS Others'), ('pam50:Basal', 'Basal VS Others'))))
	sample_option = forms.ChoiceField(label='',widget=forms.Select,required=True, choices=choice_option)


class Pathway_option(forms.Form):

	pathways = PathwayInfo.objects.all().values('pathway_name').distinct().values_list('pathway_name', flat=True)
	pathways = [str(x) for x in pathways if str(x) is not 'NULL']

	pathway_choice = [(i,i) for i in pathways]
	pathway_select = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs={'size':'20','style': 'font-size: 12px'}), label='Select Pathways ', choices=pathway_choice, required=True)
	#pathway_select = forms.ModelChoiceField(widget=forms.Select(attrs={'size':'20','style': 'font-size: 12px'}), label='Select Pathways ', choices=pathway_choice, required=True)

	def clean(self):
		value = self.cleaned_data['pathway_select']
		if len(value) != 1:
			raise forms.ValidationError("You need to select 1 item only.")
		return value

class CorrInputName(forms.Form):
	name_input1 = forms.CharField(label='Name 1 ',initial='Input 1', required=False)
	name_input2 = forms.CharField(label='Name 2 ',initial='Input 2', required=False)

class SetInputName(forms.Form):
	set_name_input = forms.CharField(label='Name ',initial='Input', required=False)

pcta_updated/main/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from __future__ import unicode_literals
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, render_to_response, HttpResponseRedirect, HttpResponse, redirect, Http404
from django.contrib.auth import authenticate, login, logout
from django.db.models import Count

from django.conf import settings
from django.urls import reverse
from .models import *
from .forms import *
import StringIO
import zipfile
import glob

from PLOTS import MY_PLOT
import numpy as np
import pandas as pd
import gseapy
from scipy import stats
from celery.result import AsyncResult

from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

from multiprocessing import Process, Queue
from pcta_updated import all_expr_df, pcta_id, mra_set
from wand.image import Image
from wand.color import Color

import json
import os
import ast
import shutil
import os.path


from .tasks import association_c, set_c, survival_c, correlation_c
from celery.result import AsyncResult
import json

def poll_state(request):

	""" A view to report the progress to the user """
	data = 'Fail'
	if request.is_ajax():
		if 'task_id' in request.POST.keys() and request.POST['task_id']:
			task_id = request.POST['task_id']
			task = AsyncResult(task_id)
			data = task.result or task.state
		else:
			data = 'No task_id in the request;'
	else:
		data = 'This is not an ajax request'

	json_data = json.dumps(data)
	print json_data

	return HttpResponse(json_data, content_type='application/json')

################PAGE VIEW################
def initial_change(request):
	pathway_input = Pathway_option(request.POST)
	if request.method == 'POST':

		if pathway_input.is_valid():
			if request.POST['input_type']=='assoc':
				pathway_list = request.POST.getlist('pathway_select')
				for x in pathway_list:
					temp_genes = PathwayGenes.objects.filter(pathway_name=x).values_list('entrez_id',flat=True)
					temp_genes = [str(y) for y in temp_genes]
				temp_genes = "\n".join(temp_genes)
				request.session['pathway_assoc'] = temp_genes
				return redirect(reverse('main:main_template'))

			elif request.POST['input_type']=='corr1':
				pathway_list = request.POST.getlist('pathway_select')
				for x in pathway_list:
					temp_genes = PathwayGenes.objects.filter(pathway_name=x).values_list('entrez_id',flat=True)
					temp_genes = [str(y) for y in temp_genes]
				temp_genes = "\n".join(temp_genes)
				request.session['pathway_corr1'] = temp_genes
				request.session['pathway_name1'] = pathway_list[0]

				return redirect(reverse('main:main_template'))

			elif request.POST['input_type']=='corr2':
				pathway_list = request.POST.getlist('pathway_select')
				for x in pathway_list:
					temp_genes = PathwayGenes.objects.filter(pathway_name=x).values_list('entrez_id',flat=True)
					temp_genes = [str(y) for y in temp_genes]
				temp_genes = "\n".join(temp_genes)
				request.session['pathway_corr2'] = temp_genes
				request.session['pathway_name2'] = pathway_list[0]
				return redirect(reverse('main:main_template'))

			elif request.POST['input_type']=='set':
				pathway_list = request.POST.getlist('pathway_select')
				for x in pathway_list:
					temp_genes = PathwayGenes.objects.filter(pathway_name=x).values_list('entrez_id',flat=True)
					temp_genes = [str(y) for y in temp_genes]
				temp_genes = "\n".join(temp_genes)
				request.session['pathway_set'] = temp_genes
				request.session['pathway_set_name'] = pathway_list[0]
				return redirect(reverse('main:main_template'))

		else:
			msg = ''
			for key, value in pathway_input.errors.items():
				value = json.dumps(value)
				value = ast.literal_eval(str(value))
				msg = msg+" "+value[0]
			return render(request,'main/error.html',{'msg':msg})

def main_template(request):
	input_key = [key for key in request.session.keys() if key.find('pathway_')>-1]

	assoc_input = AssocInputText(request.POST)
	corr_input = CorrInputText(request.POST)
	set_input = SetInputText(request.POST)
	pathway_input = Pathway_option(request.POST)
	corr_name_input = CorrInputName(request.POST)
	set_name_input = SetInputName(request.POST)

	if request.method == 'POST':

		assoc_dat = request.POST['gene_input']
		corr_dat1 = request.POST['corr_input1']
		corr_dat2 = request.POST['corr_input2']
		set_dat = request.POST['set_input']
		request.session['analysis_type'] = request.POST['analysis_type']

		#print request.POST['pathway_select']

		if assoc_dat=='' and corr_dat1=='' and corr_dat2=='' and set_dat=='': ######no input check
			msg = "No input, try again"
			return render(request,'main/error.html',{'msg':msg})

		if request.POST['analysis_type']=='Association analysis start':

			input_g = input_process(assoc_dat)

			if len(input_g)>1000:
				msg = "Too many genes, Try it less than 1000 Genes"
				return render(request,'main/error.html',{'msg':msg})

			if input_scanning(input_g)==False:
				msg = "Gene does not exist in DB, Try another gene"
				return render(request,'main/error.html',{'msg':msg})

			request.session['gene_input']=input_g

		elif request.POST['analysis_type']=='Correlation analysis start':

			input_g1 = input_process(corr_dat1)
			input_g2 = input_process(corr_dat2)

			if len(input_g1)>1000 and len(input_g2)>1000:
				msg = "Too many genes, Try it less than 1000 Genes at both boxes"
				return render(request,'main/error.html',{'msg':msg})

			elif len(input_g1)>1000:
				msg = "Too many genes, Try it less than 1000 Genes at first box"
				return render(request,'main/error.html',{'msg':msg})

			elif len(input_g2)>1000:
				msg = "Too many genes, Try it less than 1000 Genes at second box"
				return render(request,'main/error.html',{'msg':msg})


			if len(input_g1)==0:
				msg = "At first box, Please type in gene or genelist"
				return render(request,'main/error.html',{'msg':msg})

			elif len(input_g2)==0:
				msg = "At second box, Please type in gene or genelist"
				return render(request,'main/error.html',{'msg':msg})


			if input_scanning(input_g1)==False and input_scanning(input_g2)==False:
				msg = "Gene in both boxes does not exist in DB, Try another gene"
				return render(request,'main/error.html',{'msg':msg})

			elif input_scanning(input_g1)==False:
				msg = "Gene in first box does not exist in DB, Try another gene"
				return render(request,'main/error.html',{'msg':msg})

			elif input_scanning(input_g2)==False:
				msg = "Gene in second box does not exist in DB, Try another gene"
				return render(request,'main/error.html',{'msg':msg})

			request.session['corr_input1']=input_g1
			request.session['corr_input2']=input_g2

			if request.POST['name_input1']==request.POST['name_input2']:
				request.session['corr_name_input1'] = request.POST['name_input1']
				request.session['corr_name_input2'] = request.POST['name_input2']+"_duplicated"
			else:
				request.session['corr_name_input1'] = request.POST['name_input1']
				request.session['corr_name_input2'] = request.POST['name_input2']

		elif request.POST['analysis_type']=='Set analysis start':
			input_g = input_process(set_dat)

			if len(input_g)>1000:
				msg = "Too many genes, Try it less than 1000 Genes"
				return render(request,'main/error.html',{'msg':msg})

			if len(input_g)<10:
				msg = "Input should be more than 10 genes"
				return render(request,'main/error.html',{'msg':msg})

			if input_scanning(input_g)==False:
				msg = "Gene does not exist, Try another gene"
				return render(request,'main/error.html',{'msg':msg})

			request.session['set_name_input'] = request.POST['set_name_input']
			request.session['set_input']=input_process(set_dat)

		return redirect(reverse('main:option'))

	else:

		if 'pathway_assoc' in input_key:
			assoc_input = AssocInputText(initial={'gene_input':request.session['pathway_assoc']})
		else:
			assoc_input = AssocInputText()

		if 'pathway_corr1' in input_key and 'pathway_corr2' in input_key:
			corr_name_input = CorrInputName(initial={'name_input1':request.session['pathway_name1'],'name_input2':request.session['pathway_name2']})
			corr_input = CorrInputText(initial={'corr_input1':request.session['pathway_corr1'], 'corr_input2':request.session['pathway_corr2']})
		elif ('pathway_corr1' in input_key) and ('pathway_corr2' not in input_key):
			corr_name_input = CorrInputName(initial={'name_input1':request.session['pathway_name1']})
			corr_input = CorrInputText(initial={'corr_input1':request.session['pathway_corr1']})
		elif ('pathway_corr2' in input_key) and ('pathway_corr1' not in input_key):
			corr_name_input = CorrInputName(initial={'name_input2':request.session['pathway_name2']})
			corr_input = CorrInputText(initial={'corr_input2':request.session['pathway_corr2']})
		else:
			corr_name_input = CorrInputName()
			corr_input = CorrInputText()

		if 'pathway_set' in input_key:
			set_name_input = SetInputName(initial={'set_name_input':request.session['pathway_set_name']})
			set_input = SetInputText(initial={'set_input':request.session['pathway_set']})
		else:
			set_input = SetInputText()
			set_name_input = SetInputName()

		pathway_input = Pathway_option()

	return render(request, 'main/input_page.html', {'assoc_input':assoc_input, 'corr_input':corr_input, 'set_input':set_input, 'pathway_input':pathway_input, 'corr_name_input':corr_name_input, 'set_name_input':set_name_input})

def option(request):
	input_key = [key for key in request.session.keys() if key.find('pathway_')>-1]
	for key in input_key:
		del request.session[key]

	analysis_type = request.session['analysis_type']
	#print request.session.session_key

	if analysis_type=='Association analysis start':
		optionform = AssocOptionForm(request.POST)
		if request.method=='POST':
			request.session['sample_option'] = request.POST['sample_option']
			return redirect(reverse('main:calculation'))
		else:
			optionform = AssocOptionForm()

	elif analysis_type=='Correlation analysis start':

pcta_updated/templates/main/association_result.html
{% extends 'main/main.html' %}
{% load staticfiles %}

{% block content %}
    <h2>Association Analysis</h2>
    <!--
    <form method="POST" name="filedown" action="{% url 'main:image_download' %}">
        {% csrf_token %}
        <input type="submit" class="ui-button ui-widget ui-corner-all" style="display: block; margin-bottom: 20px" value="Image Download"/>
        <input type="hidden" name="filetype" value="association" />
    </form>
    -->

    <form method="POST" name="filedown" action="{% url 'main:image_download' %}" style="display: inline">
        {% csrf_token %}
        <input type="submit" class="ui-button ui-widget ui-corner-all" style="display: inline-block; margin-bottom: 20px" value="Image Download"/>
        <input type="hidden" name="filetype" value="association" />
    </form>

    <form method="POST" name="filedown" action="{% url 'main:image_download' %}" style="display: inline">
        {% csrf_token %}
        <input type="submit" class="ui-button ui-widget ui-corner-all" style="display: inline-block; margin-bottom: 20px" value="Table download"/>
        <input type="hidden" name="filetype" value=".tsv" />
    </form>

    <div style="display: block; width: 80%; height: 50%; margin-top: 10px">
        <fieldset>
        <legend for="lolli" ><b>Lollipop Plot</b></legend>
            <p><b>One-way ANOVA test between subsets: F-value = {{ table_result1.0.0 }}, P-value = {{ table_result1.0.1 }}</b></p>
        <img name="lolli" src="{% static result.0 %}" style="width: 100%"/>

        </fieldset>
    </div>

    <div class="row" style="width:80%; height: 50%; ">
    <div class="col">
        <fieldset>
        <legend for="violin" ><b>Box Plot</b></legend>
        <img name="violin"src="{% static result.1 %}" style="width: 100%"/>

            <h4>Ranksums test between subsets</h4>
        <table id="assoresult2" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Test groups</th>
                    <th>Statistics</th>
                    <th>p-value</th>
                </tr>
            </thead>
            <tbody>
                {% for td2 in table_result2 %}
                <tr>
                    {% for d in td2 %}
                        <td>{{ d }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </fieldset>
    </div>

    <div class="col">
        <fieldset>
        <legend for="histo"><b>Histogram Plot</b></legend>
        <img name="histo" src="{% static result.2 %}" style="width: 100%"/>

        </fieldset>
    </div>
    </div>

{% endblock content %}

pcta_updated/templates/main/bcr_result.html
{% extends 'main/main.html' %}
{% load staticfiles %}

{% block content %}
    <h2>Biochemical Recurrence Free-Time Analysis</h2>

    <form method="POST" name="filedown" action="{% url 'main:image_download' %}" style="display: inline">
        {% csrf_token %}
        <input type="submit" class="ui-button ui-widget ui-corner-all" style="display: inline-block; margin-bottom: 20px" value="Image Download"/>
        <input type="hidden" name="filetype" value="bcr_analysis" />
    </form>

    <form method="POST" name="filedown" action="{% url 'main:image_download' %}" style="display: inline">
        {% csrf_token %}
        <input type="submit" class="ui-button ui-widget ui-corner-all" style="display: inline-block; margin-bottom: 20px" value="Table download"/>
        <input type="hidden" name="filetype" value=".tsv" />
    </form>

    <br/>

    <!--<div style="display: inline-block; width: 40%; height: 80%; padding-bottom: 50px">-->
    <div style="display: block; width: 50%; min-width: 350px; height: 40%; padding-top: 10px">
        <fieldset>
        <legend for="GSE40272" ><b>GSE40272</b></legend>

        <h4>Kaplan-Meier Plot</h4>
        <img name="GSE40272"src="{% static result.0 %}" style="width: 100%"/>
        <h4>Cox Proportional Hazard Regression Analysis</h4>
        <table id="coxresult1" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th name="vt">Variable type</th>
                    <th>Variable</th>
                    <th>Coefficient</th>
                    <th>Hazard Ratio(95%CI)</th>
                    <th>P-value</th>
                    <th>C-index</th>
                </tr>
            </thead>
            <tbody>
                {% for td1 in table_result1 %}
                <tr>
                    {% for d in td1 %}
                        <td>{{ d }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </fieldset>
    </div>

    <!--<div style="display: inline-block; width: 40%; height: 80%; padding-bottom: 50px">-->
    <div style="display: block; width: 50%; min-width: 350px; height: 40%; padding-top: 50px; padding-bottom: 50px">
        <fieldset>
        <legend for="GSE70769"><b>GSE70769</b></legend>

        <h4>Kaplan-Meier Plot</h4>
        <img name="GSE70769" src="{% static result.1 %}" style="width: 100%"/>

        <h4>Cox Proportional Hazard Regression Analysis</h4>
        <table id="coxresult2" class="display" cellspacing="0" width="100%" >
            <thead>
                <tr>
                    <th name="vt">Variable type</th>
                    <th>Variable</th>
                    <th>Coefficient</th>
                    <th>Hazard Ratio(95%CI)</th>
                    <th>P-value</th>
                    <th>C-index</th>
                </tr>
            </thead>
            <tbody>
                {% for td2 in table_result2 %}
                <tr>
                    {% for d in td2 %}
                        <td>{{ d }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </fieldset>
    </div>

{% endblock content %}

pcta_updated/templates/main/loading.html
{% extends 'main/main.html' %}
{% load staticfiles %}

{% block content %}
 <style>
  .progress {
   width:50%;
   background:#FFFFFF;
  }
  .bar {
   height:15px;
   width:0%;
   background:#0080ff;
   text-align:right;
  }
 </style>


<div class="status" style="margin-top: 20%">
    <p><span id="user-count"></span></p>
    {% if task_id %}
        <div align="left" class="progress">
            <div align="left" class="bar"></div>
        </div>
    {% endif %}
</div>


<script type="text/javascript">
   var poll_xhr;
   var willstop = 0;
  (function(){
    var poll = function(){
      var json_dump = "{{ data }}";
      var task_id = "{{task_id}}";
      var passing_url ="{{ pass_to }}";

      console.log(task_id);
      poll_xhr = $.ajax({
          url:'poll_state',
          type: 'POST',
          data: {
              task_id: task_id,
              csrfmiddlewaretoken: "{{csrf_token}}",
          },
          success: function(result) {
              if (result.process_percent == null || result.process_percent == undefined ) {
                  willstop = 1;
                  document.getElementById("user-count").textContent="DONE";
                  jQuery('.bar').css({'width': 100 + '%','font-family':'Raleway'});
                  jQuery('.bar').html(100 + '%');
                  if (passing_url==1){window.location.href= "{% url 'main:association_result' %}";}
                  if (passing_url==2){window.location.href= "{% url 'main:bcr_result' %}";}
                  if (passing_url==3){window.location.href= "{% url 'main:correlation_result' %}";}
                  if (passing_url==4){window.location.href= "{% url 'main:set_result' %}";}
              }
              else {
                  jQuery('.bar').css({'width': result.process_percent + '%','font-family':'Raleway'});
                  jQuery('.bar').html(result.process_percent + '%');
                  document.getElementById("user-count").textContent="Calculating..";
              };
          }
      });
    };

    var refreshIntervalId = setInterval(function() {
      poll();
      if(willstop == 1){
        clearInterval(refreshIntervalId);
      }
    },500);


  })();
</script>

{% endblock content %}

pcta_updated/templates/main/loading1.html
{% extends 'main/main.html' %}
{% load staticfiles %}

{% block content %}
 <style>
  .progress {
   width:50%;
   background:#FFFFFF;
  }
  .bar {
   height:15px;
   width:0%;
   background:#0080ff;
   text-align:right;
  }
 </style>


<div class="status" style="margin-top: 20%">
    <p><span id="user-count"></span></p>
    {% if task_id %}
        <div align="left" class="progress">
            <div align="left" class="bar"></div>
        </div>
    {% endif %}
</div>


<script type="text/javascript">
   var poll_xhr;
   var willstop = 0;
  (function(){
    var poll = function(){
      var json_dump = "{{ data }}";
      var task_id = "{{task_id}}";
      var passing_url ="{{ pass_to }}";

      console.log(task_id);
      poll_xhr = $.ajax({
          url:'poll_state',
          type: 'POST',
          data: {
              task_id: task_id,
              csrfmiddlewaretoken: "{{csrf_token}}",
          },
          success: function(result) {
              if (result.process_percent1 == null || result.process_percent1 == undefined ) {
                  willstop = 1;
                  document.getElementById("user-count").textContent="DONE";
                  jQuery('.bar').css({'width': 100 + '%','font-family':'Raleway'});
                  jQuery('.bar').html(100 + '%');
                  if (passing_url==1){window.location.href= "{% url 'main:association_result' %}";}
                  if (passing_url==2){window.location.href= "{% url 'main:bcr_result' %}";}
                  if (passing_url==3){window.location.href= "{% url 'main:correlation_result' %}";}
                  if (passing_url==4){window.location.href= "{% url 'main:set_result' %}";}
              }
              else {
                  jQuery('.bar').css({'width': result.process_percent1 + '%','font-family':'Raleway'});
                  jQuery('.bar').html(result.process_percent1 + '%');
                  document.getElementById("user-count").textContent="Calculating..";
              };
          }
      });
    };

    var refreshIntervalId = setInterval(function() {
      poll();
      if(willstop == 1){
        clearInterval(refreshIntervalId);
      }
    },500);


  })();
</script>

{% endblock content %}

pcta_updated/templates/main/loading3.html
{% extends 'main/main.html' %}
{% load staticfiles %}

{% block content %}
 <style>
  .progress {
   width:50%;
   background:#FFFFFF;
  }
  .bar {
   height:15px;
   width:0%;
   background:#0080ff;
   text-align:right;
  }
 </style>


<div class="status" style="margin-top: 20%">
    <p><span id="user-count"></span></p>
    {% if task_id %}
        <div align="left" class="progress">
            <div align="left" class="bar"></div>
        </div>
    {% endif %}
</div>


<script type="text/javascript">
   var poll_xhr;
   var willstop = 0;
  (function(){
    var poll = function(){
      var json_dump = "{{ data }}";
      var task_id = "{{task_id}}";
      var passing_url ="{{ pass_to }}";

      console.log(task_id);
      poll_xhr = $.ajax({
          url:'poll_state',
          type: 'POST',
          data: {
              task_id: task_id,
              csrfmiddlewaretoken: "{{csrf_token}}",
          },
          success: function(result) {
              if (result.process_percent3 == null || result.process_percent3 == undefined ) {
                  willstop = 1;
                  document.getElementById("user-count").textContent="DONE";
                  jQuery('.bar').css({'width': 100 + '%','font-family':'Raleway'});
                  jQuery('.bar').html(100 + '%');
                  if (passing_url==1){window.location.href= "{% url 'main:association_result' %}";}
                  if (passing_url==2){window.location.href= "{% url 'main:bcr_result' %}";}
                  if (passing_url==3){window.location.href= "{% url 'main:correlation_result' %}";}
                  if (passing_url==4){window.location.href= "{% url 'main:set_result' %}";}
              }
              else {
                  jQuery('.bar').css({'width': result.process_percent3 + '%','font-family':'Raleway'});
                  jQuery('.bar').html(result.process_percent3 + '%');
                  document.getElementById("user-count").textContent="Calculating..";
              };
          }
      });
    };

    var refreshIntervalId = setInterval(function() {
      poll();
      if(willstop == 1){
        clearInterval(refreshIntervalId);
      }
    },500);


  })();
</script>

{% endblock content %}